# Generated by Django 3.1 on 2020-09-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froshwall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(),
        ),
    ]
