# Generated by Django 3.1 on 2020-09-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froshwall', '0002_auto_20200920_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
        migrations.AddField(
            model_name='tweet',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
