# Generated by Django 3.1 on 2020-08-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whodunit', '0002_question_current_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='minimum_points',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='question',
            name='point_decrement',
            field=models.IntegerField(default=5),
        ),
    ]
