# Generated by Django 3.1 on 2020-08-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whodunit', '0004_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='story',
            field=models.CharField(choices=[('space', 'space'), ('murder', 'murder'), ('vexed', 'vexed')], default='space', max_length=100),
            preserve_default=False,
        ),
    ]
