# Generated by Django 3.1 on 2020-08-12 04:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rollNumber", models.CharField(default="", max_length=100)),
                ("fullName", models.CharField(default="", max_length=150)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            (
                                "Biomedical Engineering (BME)",
                                "Biomedical Engineering (BME)",
                            ),
                            ("Biotechnology (BT)", "Biotechnology (BT)"),
                            (
                                "Chemical Engineering (CHE)",
                                "Chemical Engineering (CHE)",
                            ),
                            ("Civil Engineering (CIE)", "Civil Engineering (CIE)"),
                            (
                                "Computer Science and Business systems (COBS)",
                                "Computer Science and Business systems (COBS)",
                            ),
                            (
                                "Computer Engineering (COE)",
                                "Computer Engineering (COE)",
                            ),
                            (
                                "Computer Science & Engineering (Patiala Campus) (COPC)",
                                "Computer Science & Engineering (Patiala Campus) (COPC)",
                            ),
                            (
                                "Computer Science & Engineering (Derabassi Campus) (COSE)",
                                "Computer Science & Engineering (Derabassi Campus) (COSE)",
                            ),
                            (
                                "Electronics & Communication Engineering (ECE)",
                                "Electronics & Communication Engineering (ECE)",
                            ),
                            (
                                "Electrical and Computer Engineering (ELC)",
                                "Electrical and Computer Engineering (ELC)",
                            ),
                            (
                                "Electronics (Instrumentation & Control) Engineering (EIC)",
                                "Electronics (Instrumentation & Control) Engineering (EIC)",
                            ),
                            (
                                "Electrical Engineering (ELE)",
                                "Electrical Engineering (ELE)",
                            ),
                            (
                                "Electronics and Computer Engineering (ENC)",
                                "Electronics and Computer Engineering (ENC)",
                            ),
                            ("Mechatronics (MEC)", "Mechatronics (MEC)"),
                            (
                                "Mechanical Engineering (MEE)",
                                "Mechanical Engineering (MEE)",
                            ),
                            (
                                "Mechanical Engineering (Production) (MPE)",
                                "Mechanical Engineering (Production) (MPE)",
                            ),
                            (
                                "Dual-Degree BE-MBA (Electronics & Communication Engineering) (BEMBA-ECE)",
                                "Dual-Degree BE-MBA (Electronics & Communication Engineering) (BEMBA-ECE)",
                            ),
                            (
                                "Dual-Degree BE-MBA (Mechanical Engineering) (BEMBA-MEE)",
                                "Dual-Degree BE-MBA (Mechanical Engineering) (BEMBA-MEE)",
                            ),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        default="Not Applicable",
                        max_length=150,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Non Binary", "Non Binary"),
                            ("NIL", "Prefer Not Say"),
                        ],
                        default="NIL",
                        max_length=100,
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("points", models.IntegerField(default=0)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
