# Generated by Django 3.1 on 2020-08-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='whatsapp_link',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
