# Generated by Django 3.1 on 2020-09-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_student_whatsapp_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
