# Generated by Django 3.1 on 2020-09-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_student_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
