# Generated by Django 3.1 on 2020-09-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20200908_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='firebase_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
