# Generated by Django 3.1 on 2020-09-14 00:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_student_firebase_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 14, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='9872466977', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNumber',
            field=models.CharField(default='TIET-O-******', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='whatsapp_link',
            field=models.CharField(blank=True, default='https://froshtiet.com/coming-soon/', max_length=1024, null=True),
        ),
    ]
