# Generated by Django 3.1 on 2020-08-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_timelineevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='icon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
