# Generated by Django 3.1 on 2020-09-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_auto_20200828_1257"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourPicture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image_link", models.TextField()),
            ],
        ),
    ]
