# Generated by Django 3.1 on 2020-08-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='game_of_wits_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='whodunit_score_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='whodunit_score_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='whodunit_score_3',
            field=models.IntegerField(default=0),
        ),
    ]
