# Generated by Django 3.1 on 2020-08-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20200818_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='whodunit_level_coverage',
            field=models.IntegerField(default=0),
        ),
    ]
