# Generated by Django 3.1 on 2020-08-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_auto_20200818_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='whodunit_score_1',
            new_name='wh_score_murder',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='whodunit_score_2',
            new_name='wh_score_space',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='whodunit_score_3',
            new_name='wh_score_vexed',
        ),
    ]
